// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdImgDjTMVTMGugEpHj0uaQy0nwkB1lUk',
    appId: '1:954442711725:web:15f82211524b8f9f767c24',
    messagingSenderId: '954442711725',
    projectId: 'listasflutter',
    authDomain: 'listasflutter.firebaseapp.com',
    storageBucket: 'listasflutter.appspot.com',
    measurementId: 'G-ZJ0PJJLETG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcXxlqDMtA5MIQt7af9JrXrky5L67Eh74',
    appId: '1:954442711725:android:23ae22c01eec194d767c24',
    messagingSenderId: '954442711725',
    projectId: 'listasflutter',
    storageBucket: 'listasflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfHIyDIQJ9BpUtfe8BGLXo4HI1v7vBxFg',
    appId: '1:954442711725:ios:e28cdfb25013fc15767c24',
    messagingSenderId: '954442711725',
    projectId: 'listasflutter',
    storageBucket: 'listasflutter.appspot.com',
    iosClientId: '954442711725-atcq4tqigcqp75q54632dkrd72n3pg37.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfHIyDIQJ9BpUtfe8BGLXo4HI1v7vBxFg',
    appId: '1:954442711725:ios:e28cdfb25013fc15767c24',
    messagingSenderId: '954442711725',
    projectId: 'listasflutter',
    storageBucket: 'listasflutter.appspot.com',
    iosClientId: '954442711725-atcq4tqigcqp75q54632dkrd72n3pg37.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
