// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnbrZZtLFXMEsCM5joYvmhSICtrhLLpO4',
    appId: '1:912310514458:web:4d897d91f48561c9cf32a3',
    messagingSenderId: '912310514458',
    projectId: 'flutterapp-99a76',
    authDomain: 'flutterapp-99a76.firebaseapp.com',
    storageBucket: 'flutterapp-99a76.appspot.com',
    measurementId: 'G-QJL9P367M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT5t8H-Ray18gIqjQGmE_yQaqRlYhbkAA',
    appId: '1:912310514458:android:a3daa51e61f075fbcf32a3',
    messagingSenderId: '912310514458',
    projectId: 'flutterapp-99a76',
    storageBucket: 'flutterapp-99a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0v9YY5HEvlQlCYi45ZDaqvUKfHD58Vp0',
    appId: '1:912310514458:ios:154f4c9eebe6f702cf32a3',
    messagingSenderId: '912310514458',
    projectId: 'flutterapp-99a76',
    storageBucket: 'flutterapp-99a76.appspot.com',
    iosClientId: '912310514458-ekkhvcgfiqoegc02d95dj1phvvhp40nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0v9YY5HEvlQlCYi45ZDaqvUKfHD58Vp0',
    appId: '1:912310514458:ios:154f4c9eebe6f702cf32a3',
    messagingSenderId: '912310514458',
    projectId: 'flutterapp-99a76',
    storageBucket: 'flutterapp-99a76.appspot.com',
    iosClientId: '912310514458-ekkhvcgfiqoegc02d95dj1phvvhp40nj.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication3',
  );
}
